name: Flujo de trabajo para las tareas de construcci贸n y test
on:
  workflow_dispatch:
  push:
    branches: [ juapalesp ]
  pull_request:
    branches: [ juapalesp ]
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Construyendo y probando el c贸digo
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Mostrando uvus por pantalla
        run: echo "juapalesp."
  Test:
    runs-on: ubuntu-latest
needs: Build
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Ejecutando los test del c贸digo
        run: |
          chmod +x gradlew        
          ./gradlew test
      - name: Mostrando uvus por pantalla
        run: echo "juapalesp."
  Publish:
    runs-on: ubuntu-latest
needs: Test
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Ejecutando los test del c贸digo
        run: |
          chmod +x gradlew        
          ./gradlew publish
      - name: Mostrando uvus por pantalla
        run: echo "juapalesp."
