name: Flujo de trabajo para las tareas de construcción y test
on:
  push:
    branches: [ arreglosJunio ]
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Construyendo y probando el código
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Mostrando uvus por pantalla
        run: echo "juapalesp."
  Test:
    runs-on: ubuntu-latest
needs: Build
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Ejecutando los test del código
        run: |
          chmod +x gradlew        
          ./gradlew test
      - name: Mostrando uvus por pantalla
        run: echo "juapalesp."
